sudo: required
services:
  - docker

before_install:
  - docker build -t aaquibnaved/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aaquibnaved/react-test npm test -- --coverage

after_success:
  - docker build -t aaquibnaved/multi-client ./client
  - docker build -t aaquibnaved/multi-nginx ./nginx 
  - docker build -t aaquibnaved/multi-server ./server 
  - docker build -t aaquibnaved/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aaquibnaved/multi-client
  - docker push aaquibnaved/multi-nginx
  - docker push aaquibnaved/multi-server
  - docker push aaquibnaved/multi-worker